<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYZepxWV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYZepxWV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYZepxWV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYZepxWV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYZepxWV\App_KernelDevDebugContainer([
    'container.build_hash' => 'YZepxWV',
    'container.build_id' => '6ab58175',
    'container.build_time' => 1637749306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYZepxWV');
