<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJGzWSRX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJGzWSRX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJGzWSRX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJGzWSRX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJGzWSRX\App_KernelDevDebugContainer([
    'container.build_hash' => 'JGzWSRX',
    'container.build_id' => '2904ffb9',
    'container.build_time' => 1638797013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJGzWSRX');
